var FavoriteColor = "Blue";
console.log(FavoriteColor);
var Greeting = "Hello World";
console.log(Greeting);
var camelCase = "camelCase";
console.log(camelCase);
var snake_case = "snake_case";
console.log(snake_case);
var PascalCase = "PascalCase";
console.log(PascalCase);
